export const EXPLORER_ACTIONS = {
  SET_TREE: 'SET_TREE',
  ADD_NODE: 'ADD_NODE',
  EDIT_NODE: 'EDIT_NODE',
  DELETE_NODE: 'DELETE_NODE',
  SELECT_NODE: 'SELECT_NODE',
  TOGGLE_EXPANDED: 'TOGGLE_EXPANDED',
  SET_EDITING: 'SET_EDITING',
  SET_EXPANDED: 'SET_EXPANDED',
}
